import pandas as pd
import yfinance as yf
from datetime import datetime
from sklearn.ensemble import RandomForestClassifier

# --- 1. データ取得機能（元 fetch_data.py） ---
def get_data(ticker="AAPL", start="2015-01-01"):
    print(f"Fetching data for {ticker}...")
    df = yf.download(ticker, start=start, progress=False)
    
    # エラー回避：ヘッダーが2段になっている場合の修正
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
        
    return df

# --- 2. AI予測機能（特徴量エンジニアリング） ---
def add_features(df):
    df = df.copy()
    # 変化率
    df["Return"] = df["Close"].pct_change()
    # 移動平均
    df["SMA_5"] = df["Close"].rolling(window=5).mean()
    df["SMA_25"] = df["Close"].rolling(window=25).mean()
    # 乖離率
    df["Deviation"] = (df["SMA_5"] - df["SMA_25"]) / df["SMA_25"]
    
    # 目的変数（明日の終値が上がるか？）
    df["Target"] = (df["Close"].shift(-1) > df["Close"]).astype(int)
    
    df.dropna(inplace=True)
    return df

# --- 3. 結果書き込み機能 ---
def update_readme(prediction_text, confidence):
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    content = f"""# 📈 Stock Prediction AI
    
**Latest Prediction for AAPL**
- 🕒 Updated: {now} (UTC)
- 🔮 Prediction: **{prediction_text}**
- 🤖 Confidence: {confidence:.1f}%

---
*This prediction is automatically generated by GitHub Actions.*
"""
    with open("README.md", "w", encoding="utf-8") as f:
        f.write(content)
    print("README.md has been updated!")

# --- メイン処理 ---
def main():
    # 1. データ取得
    try:
        df = get_data("AAPL")
        if df.empty:
            print("Error: No data fetched.")
            return
    except Exception as e:
        print(f"Error fetching data: {e}")
        return

    # 2. データ加工
    df_processed = add_features(df)
    
    features = ["Return", "Deviation"]
    X = df_processed[features]
    y = df_processed["Target"]
    
    # 学習（昨日までのデータ）と予測（今日のデータ）
    X_train = X.iloc[:-1]
    y_train = y.iloc[:-1]
    X_latest = X.iloc[-1:]
    
    # 3. モデル作成 & 学習
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)
    
    # 4. 予測実行
    prediction = model.predict(X_latest)[0]
    probability = model.predict_proba(X_latest)[0]
    
    result = "UP 📈" if prediction == 1 else "DOWN 📉"
    confidence = probability[prediction] * 100
    
    print(f"Prediction: {result} ({confidence:.1f}%)")
    
    # 5. README更新
    update_readme(result, confidence)

if __name__ == "__main__":
    main()
