
import pandas as pd
from datetime import datetime
from sklearn.ensemble import RandomForestClassifier
from data.fetch_data import get_data

def add_features(df):
    df = df.copy()
    df["Return"] = df["Close"].pct_change()
    df["SMA_5"] = df["Close"].rolling(window=5).mean()
    df["SMA_25"] = df["Close"].rolling(window=25).mean()
    df["Deviation"] = (df["SMA_5"] - df["SMA_25"]) / df["SMA_25"]
    # 明日の予測
    df["Target"] = (df["Close"].shift(-1) > df["Close"]).astype(int)
    df.dropna(inplace=True)
    return df

def update_readme(prediction_text, confidence):
    """
    README.md を書き換えて、最新の予測を表示する関数
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # 表示する内容（Markdown形式）
    content = f"""# 📈 Stock Prediction AI
    
**Latest Prediction for AAPL**
- 🕒 Updated: {now} (UTC)
- 🔮 Prediction: **{prediction_text}**
- 🤖 Confidence: {confidence:.1f}%

---
*This prediction is automatically generated by GitHub Actions.*
"""
    
    # ファイルに書き込む
    with open("README.md", "w", encoding="utf-8") as f:
        f.write(content)
    print("README.md has been updated!")

def main():
    print("--- 1. Data Fetching ---")
    df = get_data("AAPL")
    
    print("--- 2. Feature Engineering ---")
    df_processed = add_features(df)
    
    features = ["Return", "Deviation"]
    X = df_processed[features]
    y = df_processed["Target"]
    
    X_train = X.iloc[:-1]
    y_train = y.iloc[:-1]
    X_latest = X.iloc[-1:] 
    
    print("--- 3. Training ---")
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)
    
    print("--- 4. Prediction ---")
    prediction = model.predict(X_latest)[0]
    probability = model.predict_proba(X_latest)[0]
    
    result = "UP 📈" if prediction == 1 else "DOWN 📉"
    confidence = probability[prediction] * 100
    
    print(f"Prediction: {result} ({confidence:.1f}%)")
    
    # ★ここでREADMEを更新！
    update_readme(result, confidence)

if __name__ == "__main__":
    main()
