import pandas as pd
import yfinance as yf
from datetime import datetime, timedelta
from sklearn.ensemble import RandomForestClassifier

# --- 1. データ取得 ---
def get_data(ticker="AAPL", start="2015-01-01"):
    # 最新の日付まで取得
    df = yf.download(ticker, start=start, progress=False)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    return df

# --- 2. 特徴量エンジニアリング（5日後予測用に強化） ---
def add_features(df):
    df = df.copy()
    
    # 変化率（リターン）
    df["Return"] = df["Close"].pct_change()
    
    # 移動平均線（短期・中期・長期）
    df["SMA_5"] = df["Close"].rolling(window=5).mean()
    df["SMA_20"] = df["Close"].rolling(window=20).mean()
    df["SMA_60"] = df["Close"].rolling(window=60).mean()
    
    # 乖離率（トレンドの強さ）
    df["Deviation_Short"] = (df["Close"] - df["SMA_5"]) / df["SMA_5"]
    df["Deviation_Mid"] = (df["Close"] - df["SMA_20"]) / df["SMA_20"]
    
    # ボラティリティ（値動きの激しさ）
    df["Volatility"] = df["Close"].pct_change().rolling(window=5).std()
    
    # ★ここがプロ仕様！「5日後」を予測する
    # 5日後の終値が、今日より「1%以上」上がっていれば勝ち(1)、それ以外は負け(0)
    # ※単に上がるだけでなく「ある程度しっかり上がる」ことを狙う
    prediction_days = 5
    threshold = 0.01 # 1%
    
    future_return = (df["Close"].shift(-prediction_days) - df["Close"]) / df["Close"]
    df["Target"] = (future_return > threshold).astype(int)
    
    df.dropna(inplace=True)
    return df

# --- 3. README更新機能 ---
def update_readme(prediction_text, confidence, latest_price):
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    content = f"""# 📈 Stock Prediction AI (Professional Ver.)
    
## 🎯 Prediction for AAPL (5-Day Horizon)
AI predicts whether the price will rise **>1%** in the next 5 days.

- 🕒 **Updated:** {now} (UTC)
- 💰 **Latest Price:** ${latest_price:.2f}
- 🔮 **Prediction:** **{prediction_text}**
- 🤖 **Confidence:** {confidence:.1f}%

---
### 📊 Model Info
- **Target:** 5 days later (Event Prediction)
- **Model:** Random Forest Classifier
- *Automatically generated by GitHub Actions*
"""
    with open("README.md", "w", encoding="utf-8") as f:
        f.write(content)

# --- メイン処理 ---
def main():
    # データ取得
    try:
        df = get_data("AAPL")
        if df.empty: return
    except: return

    latest_price = df["Close"].iloc[-1]
    
    # データ加工
    df_processed = add_features(df)
    
    features = ["Return", "Deviation_Short", "Deviation_Mid", "Volatility"]
    X = df_processed[features]
    y = df_processed["Target"]
    
    # 学習用（5日前まで）と予測用（最新）
    # ※5日後予測なので、正解がわかっているのは5日前まで
    X_train = X.iloc[:-5]
    y_train = y.iloc[:-5]
    X_latest = X.iloc[-1:]
    
    # モデル学習
    # 木の深さを制限して「過学習（暗記）」を防ぐ
    model = RandomForestClassifier(n_estimators=200, max_depth=5, random_state=42)
    model.fit(X_train, y_train)
    
    # 予測
    prediction = model.predict(X_latest)[0]
    probability = model.predict_proba(X_latest)[0]
    
    # 結果の判定
    if prediction == 1:
        result = "UP 🚀 (Strong Buy)"
        confidence = probability[1] * 100
    else:
        result = "NEUTRAL / DOWN ✋ (Wait)"
        confidence = probability[0] * 100
    
    print(f"Prediction: {result} ({confidence:.1f}%)")
    
    update_readme(result, confidence, latest_price)

if __name__ == "__main__":
    main()
